### ISSUE TITLE
Exercise 04: Configuring RBAC permissions while using Access Policy

### ISSUE THREAD

**Issue by MSFT-MarcoEs** [MicrosoftLearning/Secure-storage-for-Azure-Files-and-Azure-Blob-Storage#1]
# Module: 04 Provide storage for a new company app
#### Step: 05

Description of issue: During the setup of the permissions, the lab requires using "Access Control (IAM)", but later it requires to use a "Vault access policy". This will not work and will generate an error later in the task 2 of the lab "Configure the storage account to use the customer managed key in the key vault". The option that needs to be select instead is "Azure role-based access control (recommended)"

Repro steps:
![image](https://github.com/MicrosoftLearning/Secure-storage-for-Azure-Files-and-Azure-Blob-Storage/assets/38212502/a5403cae-6858-464a-9bdd-40a6ab44eb97)

**Comment by staleycyn** [comment]
This has been corrected. Thank you for reporting.
